### PR TITLE
Remove invalid phone number warning on required input

### PR DESCRIPTION
**Pull request by matjkel**
This PR is related to https://github.com/edlio/cms/issues/5996. 

This 👇 block of logic is where I'm finding the cause of the above issue to lie
`if (this.parsedPhoneNumber == null) {
			return !this.hasAttribute('allow-empty');
		}`

The idea is nice, but fundamentally I don't think the component should concern itself with displaying an _Invalid phone number_ error when it hasn't parsed a number and the input is required. Instead, that sort of logic should be within the domain of the Form in which the component lives. It's also confusing as a user to see an error about an _Invalid phone number_ when the component has yet to receive any input. 

I propose we let the phone component to concern itself with number validation, etc. and the Form should be in charge of checking for empty inputs on required elements --which it is currently doing.  
_(also it's possible that I misunderstood the intent behind that block of code, if so maybe the author could clarify 😄)_

All constructive input/suggestions are welcome!

### CODE REVIEW

**Comment by lancedolan** [comment]
I agree. The intuitive purpose of `allow-empty` is a set of logic which should only be run on form submit; form submission, however that is implemented, is outside the scope of this component and it cannot know when form submission occurs. 

Let's remove _all_ references to allow-empty from uniform, including the kitchen sink documentation if it's there? I recall Cristian adding a helpful little list of all phone component attributes beneath the component in the kitchen sink.

**Comment by lancedolan** [comment]
@matjkel Something I just thought of:

Is the `allow-empty` attribute used on other uniform components? Perhaps there's an overarching goal for supporting that attribute across all our input components that I'm not aware of?

@cbhernan also has more experience with this library than me, what do you think @cbhernan ?

**Comment by cbhernan** [comment]
I'm okay with the proposed change, but I don't think we should remove `allow-empty` yet. The purpose of the attribute is to show error messages when we require a length in an input, but there are places where we should allow the submission of an empty input / replacing what's there with nothing. It's meant for immediate feedback.

The problem, if I understand, is a premature error message, which should be resolvable by checking if an input is dirty/has been touched yet.

When the form is submitted, you can always trigger the function `document.getElementById("contact_0").isPhoneValid()` to check if the component is mad at something.

Also `isPhoneValid` needs to be renamed because if a phone number *is* valid I'm getting a `false` but if it's not valid I get `true`

**Comment by cbhernan** [comment]
Also, when making changes, please ensure that they still work as expected everywhere used. 

For this component:
- Voice
- Forms
- Settings > Contact

I think that's it.

**Comment by matjkel** [comment]
> Also isPhoneValid needs to be renamed because if a phone number is valid I'm getting a false but if it's not valid I get true

This was bugging me too. What would you think is better to name it `isPhoneInvalid`? That seems clunky  🤔

**Pull request merged**
